name: .NET Build

on:
  push:
  pull_request:
    branches: [ "main" ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.cshtml'    

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use
  
jobs:
  build:

    name: Build All Projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution:
        - Part 3 - Cost Optimization/azd-sample/src/AppConfigurationReader.sln
        - Part 4 - Reliability/finished/Relecloud.sln
        - Part 4 - Reliability/src/Relecloud.sln
        - Part 5 - Security/azd-sample/src/AppConfigurationReader.sln
        - Part 5 - Security/finished/src/AppConfigurationReader.sln
        - Part 7 - Performance Efficiency/start/Relecloud.sln
        - Part 7 - Performance Efficiency/finished/Relecloud.sln
        - Reference App/src/Relecloud.sln

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Build Step - ${{ matrix.solution }}
      run: dotnet build "${{ matrix. Solution }}"
