name: .NET Build

on:
  push:
  pull_request:
    branches: [ "main" ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.cshtml'    

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use
  
jobs:
  build:

    name: Build All Projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution:
        - Part3 - Cost Optimization/azd-sample/src
        - Part4 - Reliability/finished
        - Part4 - Reliability/src
        - Part5 - Security/azd-sample/src
        - Part5 - Security/finished/src
        - Part7 - Performance Efficiency/finished
        - Part7 - Performance Efficiency/start
        - Reference App/src

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Build Step - ${{ matrix.solution }}
      run: dotnet build "${{ matrix.solution }}"
